name: Publish to Docker Hub

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up docker-buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: v0.4.1
          qemu-version: 4.2.0-7
      - name: build & publish
        run: |
          docker login \
            --username jayfong \
            --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker buildx build \
            --platform linux/arm/v7 \
            --tag jayfong/yapi:latest .
